server:
  port: 8502 # 端口

spring:
  application:
    name: xiaoxiao-bbs # 应用名称

  profiles:
    active: dev

  cloud:
    nacos:
      config:
        enabled: true # 如果不想使用 Nacos 进行配置管理，设置为 false 即可
        server-addr: localhost:8848 # Nacos 配置中心 地址
        namespace: ${spring.profiles.active} # 命名空间
        group: xiaoxiao-bbs # 组，默认为 DEFAULT_GROUP
        file-extension: yaml # 配置内容的数据格式，默认为 properties

  config:
    import:
      - optional:nacos:xiaoxiao-bbs-${spring.profiles.active}.yml
      - optional:nacos:xiaoxiao-common-${spring.profiles.active}.yml?group=xiaoxiao-common # group=xiaoxiao-common 指定分组
